repos:
  - repo: local
    hooks:
      - id: rust-tests
        name: Run Rust tests
        entry: cargo test --workspace
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      
      - id: rust-clippy
        name: Run Clippy
        entry: cargo clippy --workspace -- -D warnings
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      
      - id: rust-fmt
        name: Run rustfmt
        entry: cargo fmt --workspace -- --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      
      - id: wasm-tests
        name: Run WASM tests
        entry: cd crates/tailwind-rs-wasm && wasm-pack test --node
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]