[package]
name = "tailwind-rs-simple-ssr"
version = "0.1.0"
edition = "2021"
authors = ["Tailwind-RS Team"]
license = "MIT"
description = "Simple Server-Side Rendering demo for Tailwind-RS with Rust"
rust-version = "1.89.0"

[[bin]]
name = "simple-ssr"
path = "simple_ssr.rs"

[dependencies]
# Tailwind-RS
tailwind-rs-core = { workspace = true }