# Cargo nextest configuration for tailwind-rs
# Optimized for TDD workflow and comprehensive testing

[profile.default]
# Test execution settings
retries = 2
slow-timeout = { period = "60s", terminate-after = 2 }
leak-timeout = "5s"
test-threads = "num-cpus"

# Output settings
failure-output = "immediate-final"
success-output = "never"
status-level = "fail"

# Performance settings
partition-strategy = "count"
partition-size = 1

[profile.tdd]
# TDD-specific settings for rapid development
retries = 0
slow-timeout = { period = "30s", terminate-after = 1 }
test-threads = "num-cpus"
failure-output = "immediate-final"
success-output = "never"
status-level = "fail"
partition-strategy = "count"
partition-size = 1

# Test organization
[[profile.default.overrides]]
filter = "test(test_|integration_)"
slow-timeout = { period = "30s", terminate-after = 1 }

[[profile.default.overrides]]
filter = "test(property_)"
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.default.overrides]]
filter = "test(comprehensive_)"
slow-timeout = { period = "120s", terminate-after = 3 }