[package]
name = "tailwind-rs-leptos-demo-wasm-fixed"
version = "0.1.0"
edition = "2021"
authors = ["Tailwind-RS Team"]
license = "MIT"
description = "WASM-fixed Leptos demo using tailwind-rs-wasm crate"
rust-version = "1.89.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib_wasm_fixed.rs"

[dependencies]
# Leptos dependencies
leptos = { version = "0.8.8", features = ["csr"] }

# Use the working tailwind-rs-wasm crate
tailwind-rs-wasm = "0.1.0"

# Web dependencies (only for WASM builds)
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.99"
web-sys = "0.3.77"
js-sys = "0.3.77"
console_error_panic_hook = "0.1.7"
