[package]
name = "tailwind-rs-leptos-demo-minimal"
version = "0.1.0"
edition = "2021"
authors = ["Tailwind-RS Team"]
license = "MIT"
description = "Minimal Leptos WASM demo without problematic dependencies"
rust-version = "1.89.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib_minimal.rs"

[dependencies]
# Minimal Leptos dependencies
leptos = { version = "0.8.8", features = ["csr"] }

# Web dependencies (only for WASM builds)
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.99"
web-sys = "0.3.77"
js-sys = "0.3.77"
console_error_panic_hook = "0.1.7"
