name: Regression Prevention Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    
    - name: Run unit tests
      run: cargo test --workspace --verbose
    
    - name: Run clippy
      run: cargo clippy --workspace -- -D warnings
    
    - name: Check formatting
      run: cargo fmt --workspace -- --check
    
    - name: Run property-based tests
      run: cargo test --verbose

  performance:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Run performance tests
      run: cargo test --verbose
    
    - name: Check bundle size
      run: |
        cd crates/tailwind-rs-wasm
        wasm-pack build --target web --out-dir pkg --release
        ls -la pkg/tailwind_rs_wasm_bg.wasm
        # Fail if bundle size exceeds 25KB
        if [ $(stat -c%s pkg/tailwind_rs_wasm_bg.wasm) -gt 25000 ]; then
          echo "Bundle size exceeds 25KB limit"
          exit 1
        fi

  browser-tests:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    
    - name: Install dependencies
      run: |
        cd crates/tailwind-rs-wasm
        pnpm install
    
    - name: Build WASM
      run: |
        cd crates/tailwind-rs-wasm
        wasm-pack build --target web --out-dir pkg --release
    
    - name: Install Playwright
      run: |
        cd crates/tailwind-rs-wasm
        pnpm install -D @playwright/test
    
    - name: Install Playwright browsers
      run: |
        cd crates/tailwind-rs-wasm
        pnpm exec playwright install
    
    - name: Run Playwright tests
      run: |
        cd crates/tailwind-rs-wasm
        pnpm exec playwright test --project=chromium --project=firefox --project=webkit
